name: Build React-Wallet webapp

on:
  push:

jobs:
  build-android-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install root dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Install dependencies
        run: |
          cd ./apps/react-wallet
          npm ci

      - name: Build extension
        run: |
          cd ./apps/react-wallet
          npm run build

